name: Provision Infrastructure - Staging

on:
  push:
    branches:
      - main
    paths:
      - '**.bicep'

env:
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP_STAGING }}
  STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME_STAGING }}
  APP_INSIGHTS_ACCOUNT_NAME: ${{ vars.APP_INSIGHTS_ACCOUNT_NAME_STAGING }}

jobs:
  provisioning:
    name: Provision infrastructure to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS_STAGING }} 
      - name: Provision Infrastructure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --name ftaaas --template-file infra/deploytostorageaccount.bicep --parameters accountName=$STORAGE_ACCOUNT_NAME appInsightsName=$APP_INSIGHTS_ACCOUNT_NAME skuName=Standard_LRS -g $RESOURCE_GROUP
      - name: logout
        run: |
          az logout
        if: always()
